http {
	server {
		listen 127.0.0.1:8080 default_server;
		server_name localhost;

		root /home/takosuke/42/webserv_sandbox/www;

		error_page 404 /404.html;
		error_page 500 501 502 503 504 /50x.html;

		location /cgi-bin {
			root /home/takosuke/42/webserv_sandbox/www;
			cgi_pass /usr/bin/python3;

			# Extra env vars forwarded to the CGI process
			cgi_param APP_ENV testing;
			cgi_param SECRET_KEY hunter2;
		}

		location / {
			root /home/takosuke/42/webserv_sandbox/www;
		}
	}
}
