http {
	upload_directory __WWWROOT__/upload upload;
	server {
		listen 127.0.0.1:8080 default_server;
		server_name localhost;

		error_page 400 /errorpages/400.html;
		error_page 401 /errorpages/401.html;
		error_page 403 /errorpages/403.html;
		error_page 404 /errorpages/404.html;
		error_page 405 /errorpages/405.html;
		error_page 408 /errorpages/408.html;
		error_page 413 /errorpages/413.html;
		error_page 500 501 502 503 504 /errorpages/50x.html;

		location \ .jpg {
			root __WWWROOT__/imgs;
		}

		location \ .css {
			root __WWWROOT__/css;
			default_type	text/css;
		}

		root __WWWROOT__;

		location /cgi-bin/ {
			root __WWWROOT__;
			cgi_pass /usr/bin/python3;
		}

		location / {
			root __WWWROOT__;
		}
	}
}
