http {
	server {
		listen 127.0.0.1:8080 default_server;
		server_name localhost;

		root __WWWROOT__;

		# A short `return` target is enough to make starts_with_scheme()
		# read past the end of the path string.
		location /go {
			return /a;
		}

		location / {
			root __WWWROOT__;
		}
	}
}
