http {
	server {
		listen 127.0.0.1:8080 default_server;
		server_name localhost;

		root /home/takosuke/42/webserv_sandbox/www;

		error_page 404 /404.html;
		error_page 500 501 502 503 504 /50x.html;

		# Only GET is allowed here; POST/DELETE/etc. should get 405
		location /readonly {
			root /home/takosuke/42/webserv_sandbox/www;
			limit_except GET;
		}

		location / {
			root /home/takosuke/42/webserv_sandbox/www;
		}
	}
}
