http {
	upload_directory __WWWROOT__/upload upload;

	types {
		text/html	html;
		text/css	css;
		application/javascript	js;
		image/gif	gif;
		image/jpeg	jpeg jpg;
		image/png	png;
		image/svg+xml	svg;
		image/x-icon	ico;
	}
	default_type	text/plain;

	server {
		listen 127.0.0.1:8080 default_server;
		server_name localhost;

		root __WWWROOT__;

		client_max_body_size 10k;


		location \ .jpg {
			root __WWWROOT__/imgs;
		}

		location \ .css {
			root __WWWROOT__/css;
			default_type	text/css;
		}

		location /cgi-bin {
			root __WWWROOT__;
			cgi_pass /usr/bin/python3;
		}

		location / {
			root __WWWROOT__;
		}

		location upload/ {
			limit_except	GET;
		}
	}
}
