http {
	server {
		listen 127.0.0.1:8080 default_server;
		server_name timeout;

		root __WWWROOT__;

		client_max_body_size 10k;

		client_header_timeout	0;
		client_body_timeout		0;

		error_page 404 /404.html;
		error_page 500 501 502 503 504 /50x.html;
		error_page 404 =302 https://www.google.com;

		location /cgi-bin {
			root __WWWROOT__;
			cgi_pass /usr/bin/python3;
		}

		location / {
			root __WWWROOT__;
		}
	}
}
