http {
	server {
		listen 127.0.0.1:8080 default_server;
		server_name default.local;

		root __WWWROOT__;

		error_page 404 /404.html;

		location / {
			root __WWWROOT__;
		}
	}

	server {
		listen 127.0.0.1:8080;
		server_name static.local;

		root __WWWROOT__/static;

		error_page 404 /404.html;

		location / {
			root __WWWROOT__/static;
		}
	}
}
