http {
	server {
		listen 127.0.0.1:8080 default_server;
		server_name default.local;

		root /home/takosuke/42/webserv_sandbox/www;

		error_page 404 /404.html;

		location / {
			root /home/takosuke/42/webserv_sandbox/www;
		}
	}

	server {
		listen 127.0.0.1:8080;
		server_name static.local;

		root /home/takosuke/42/webserv_sandbox/www/static;

		error_page 404 /404.html;

		location / {
			root /home/takosuke/42/webserv_sandbox/www/static;
		}
	}
}
