http {
	server {
		listen 127.0.0.1:8080 default_server;
		server_name localhost;

		root /home/abronner/projects/webserv;

		error_page 404 =302 "http://www.goggle.com";
		error_page 500 501 502 503 504 /50x.html;

		location / {
			root /home/abronner/projects/webserv;
		}

		location \ .php {
			cgi_pass	localhost:9000;

			cgi_param	TEST	$test;
		}
	}
}
