#!/usr/bin/env python3
# A CGI script that behaves itself: always 200, always HTML, works for GET
# (name in the query string) and POST (name in a urlencoded body).
# The counterpart of hello.py, which answers 400 on purpose as a test probe.
import os
import sys


def parse_pairs(blob):
    pairs = {}
    for chunk in blob.split("&"):
        if not chunk:
            continue
        key, _, value = chunk.partition("=")
        pairs[unquote(key)] = unquote(value)
    return pairs


def unquote(s):
    s = s.replace("+", " ")
    out = []
    i = 0
    while i < len(s):
        if s[i] == "%" and i + 3 <= len(s):
            try:
                out.append(chr(int(s[i + 1:i + 3], 16)))
                i += 3
                continue
            except ValueError:
                pass
        out.append(s[i])
        i += 1
    return "".join(out)


def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;")
             .replace(">", "&gt;").replace('"', "&quot;"))


method = os.environ.get("REQUEST_METHOD", "GET")
fields = parse_pairs(os.environ.get("QUERY_STRING", ""))

if method == "POST":
    raw = os.environ.get("CONTENT_LENGTH", "")
    try:
        n = int(raw) if raw else 0
    except ValueError:
        n = 0
    if n > 0:
        fields.update(parse_pairs(sys.stdin.read(n)))

name = fields.get("name", "").strip() or "stranger"

html = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hello from CGI</title>
  <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
  <div class="container">
    <h1>Hello, %(name)s!</h1>
    <p>This page was generated by a CGI script over <code>%(method)s</code>.</p>
    <p><a href="/forms.html">back to the forms</a> &middot;
       <a href="/">start page</a></p>
  </div>
</body>
</html>
""" % {"name": esc(name), "method": esc(method)}

sys.stdout.write("Content-Type: text/html\r\n")
sys.stdout.write("Status: 200 OK\r\n")
sys.stdout.write("Content-Length: " + str(len(html)) + "\r\n")
sys.stdout.write("\r\n")
sys.stdout.write(html)
sys.stdout.flush()
